project:
  type: website
  output-dir: ../docs

website:
  title: "Eric Wong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - text: Projects
        menu:
          - text: Personal
          - text: Golf Swing Analyzer
            href: projects/golf-swing-analyzer.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/eric~wong/
      - icon: github
        href: https://github.com/Eric-Wong97
      - icon: envelope
        href: mailto:eric97wong@gmail.com

format:
  html:
    lib-dir: ../eric_wong97/site_libs
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



