---
title: "Experience"
---

## Professional Experience

### Data Analyst | FPInnovations
*Vancouver, British Columbia | November 2022 - August 2025*

*   **Lead Time Reduction:** Designed and deployed scalable data pipelines using Python, SQL, and Azure across 4 major projects, reducing customer onboard and setup time from **6 months to 4 weeks**.
*   **Digitalization:** Led the design and implementation of digitalized reporting systems, increasing interdepartmental cohesion across 10 teams and reducing manual effort by **6 hours weekly**.
*   **Anomaly Modeling:** Developed, validated, and deployed machine learning models to identify and mitigate over **30 anomalies per site**, safeguarding operational integrity.
*   **Data Analysis:** Wrangled large datasets from diverse sources using Python and SQL to uncover critical insights for strategic decision-making.
*   **Azure DevOps Integration:** Led the integration of CI/CD best practices and facilitated peer reviews to advance data analytics capabilities.

### Sales Assistant | Interfor
*Burnaby, British Columbia | November 2021 - November 2022*

*   **Market Analysis:** Analyzed market data to provide key insights, contributing to a **23% revenue increase** from the previous year.
*   **Vendor Inventory Management:** Managed 8 VMI systems and leveraged Tableau to convey logistics KPIs, reducing lead times by **12% YoY**.
*   **Contract Management:** Maintained high-volume contracts ($4m/month) by leveraging LumberTrack data to forecast supply needs.

## Education

### Master of Data Science
**University of British Columbia** | *August 2025 - Present* <br>
**Relevant Coursework:** Algorithms & Data Structures, Supervised & Unsupervised Learning, Cloud Computing, Databases, Causal Inference, Spatial & Temporal Models, Advanced Machine Learning.

### Bachelor of Science
**University of British Columbia** | *September 2016 - June 2021*
